name: Publish CUI at MobileHCI 2020 workshop website ###### <<<<<<<<<<<<<<<<<< CHANGE TO APPROPRIATE NAME

on:
  # Runs on pushes and merged pull requests targeting the default branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_SIGN_KEY }}
          git_user_signingkey: true
          git_config_global: true
          git_commit_gpgsign: true
       #   workdir: './work/'
      - name: Push to website repository
        uses: acm-cui/github-action-push@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'acm-cui'
          destination-repository-name: 'website'
          user-email: 'cuitechchair@gmail.com'
          user-name: 'cuibot'
          target-branch: 'live' # This will change in the future to 'main' or equivalent
          target-directory: 'workshops/MobileHCI2020' ###### <<<<<<<<<<<<<<<<<< ENSURE YOU CHANGE THIS!!!

