name: Publish CUI Subsite website ###### <<<<<<<<<<<<<<<<<< CHANGE TO APPROPRIATE NAME

on:
  # Runs on pushes and merged pull requests targeting the default branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Push to conversationaluserinterfaces.org repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'acm-cui'
          destination-repository-name: 'website'
          user-email: 'cuitechchair@gmail.com'
          user-name: 'cuibot'
          target-branch: 'live' # This will change in the future to 'main' or equivalent
          target-directory: 'mysubsitehere' ###### <<<<<<<<<<<<<<<<<< ENSURE YOU CHANGE THIS!!!

